spring:
  application:
   name: notification-service
  mail:
   host: smtp.gmail.com
   port: 587
   username: kmrpiyush95@gmail.com
   password: nach ehyf ggwi rkis
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
    domain_name: revauniversity@info.com

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
