spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/admin/**, /api/v1/user/**
          filters:
            - AuthenticationFilter
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30

        - id: fee-service
          uri: lb://FEE-SERVICE
          predicates:
            - Path=/api/v1/fee/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
eureka:
  client:
   service-url:
    defaultZone : http://localhost:8761/eureka/
server:
  port: 8081
