spring:
  application:
    name: IDENTITY-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: kmrpiyush95@gmail.com
    password: nach ehyf ggwi rkis
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      domain_name: revauniversity@info.com
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
application:
  config:
    notification-url: http://NOTIFICATION-SERVICE/api/v1/notification